from .helpers import _get_client, _ok, _slim, _slim_list, _paginated  # noqa: F401
from .groups import (  # noqa: F401
    authentik_read,
    authentik_write,
    authentik_delete,
    authentik_flows_read,
    authentik_flows_write,
    authentik_admin,
)

# Import all tool modules so @_op-decorated functions are registered
from . import (  # noqa: F401
    version,
    read_core,
    read_providers,
    read_outposts,
    read_crypto,
    read_rbac,
    read_authenticators,
    read_property_mappings,
    read_oauth2_tokens,
    read_managed,
    read_rac,
    read_endpoints,
    read_enterprise,
    read_tenants,
    read_tasks,
    read_reports,
    read_ssf,
    read_root,
    flows_read_flows,
    flows_read_policies,
    flows_read_events,
    flows_read_stages,
    flows_read_sources,
    admin,
    write_core,
    write_providers,
    write_outposts,
    write_crypto,
    write_rbac,
    write_property_mappings,
    write_managed,
    write_rac,
    write_endpoints,
    write_enterprise,
    write_tenants,
    write_tasks,
    write_authenticators,
    flows_write_flows,
    flows_write_policies,
    flows_write_events,
    flows_write_stages,
    flows_write_sources,
    delete,
)
