"""Hand-maintained response projections and request behavior."""

from . import helpers

LIST_PROJECTIONS = {
    'authenticators_admin_duo_list': helpers.SLIM_AUTHENTICATOR_DEVICE,
    'authenticators_admin_email_list': helpers.SLIM_AUTHENTICATOR_DEVICE,
    'authenticators_admin_endpoint_list': helpers.SLIM_AUTHENTICATOR_DEVICE,
    'authenticators_admin_sms_list': helpers.SLIM_AUTHENTICATOR_DEVICE,
    'authenticators_admin_static_list': helpers.SLIM_AUTHENTICATOR_DEVICE,
    'authenticators_admin_totp_list': helpers.SLIM_AUTHENTICATOR_DEVICE,
    'authenticators_admin_webauthn_list': helpers.SLIM_AUTHENTICATOR_DEVICE,
    'authenticators_duo_list': helpers.SLIM_AUTHENTICATOR_DEVICE,
    'authenticators_email_list': helpers.SLIM_AUTHENTICATOR_DEVICE,
    'authenticators_endpoint_list': helpers.SLIM_AUTHENTICATOR_DEVICE,
    'authenticators_sms_list': helpers.SLIM_AUTHENTICATOR_DEVICE,
    'authenticators_static_list': helpers.SLIM_AUTHENTICATOR_DEVICE,
    'authenticators_totp_list': helpers.SLIM_AUTHENTICATOR_DEVICE,
    'authenticators_webauthn_list': helpers.SLIM_AUTHENTICATOR_DEVICE,
    'core_application_entitlements_list': helpers.SLIM_APP_ENTITLEMENT,
    'core_applications_list': helpers.SLIM_APP,
    'core_authenticated_sessions_list': helpers.SLIM_SESSION,
    'core_brands_list': helpers.SLIM_BRAND,
    'core_groups_list': helpers.SLIM_GROUP,
    'core_tokens_list': helpers.SLIM_TOKEN,
    'core_user_consent_list': helpers.SLIM_USER_CONSENT,
    'core_users_list': helpers.SLIM_USER,
    'crypto_certificatekeypairs_list': helpers.SLIM_CERTIFICATE,
    'endpoints_agents_connectors_list': helpers.SLIM_ENDPOINT,
    'endpoints_agents_enrollment_tokens_list': helpers.SLIM_ENDPOINT,
    'endpoints_connectors_list': helpers.SLIM_ENDPOINT,
    'endpoints_device_access_groups_list': helpers.SLIM_ENDPOINT,
    'endpoints_device_bindings_list': helpers.SLIM_ENDPOINT,
    'endpoints_devices_list': helpers.SLIM_ENDPOINT,
    'endpoints_fleet_connectors_list': helpers.SLIM_ENDPOINT,
    'endpoints_google_chrome_connectors_list': helpers.SLIM_ENDPOINT,
    'enterprise_license_list': helpers.SLIM_LICENSE,
    'events_events_list': helpers.SLIM_EVENT,
    'events_notifications_list': helpers.SLIM_NOTIFICATION,
    'events_rules_list': helpers.SLIM_NOTIFICATION_RULE,
    'events_transports_list': helpers.SLIM_NOTIFICATION_TRANSPORT,
    'flows_bindings_list': helpers.SLIM_FLOW_BINDING,
    'flows_instances_list': helpers.SLIM_FLOW,
    'managed_blueprints_list': helpers.SLIM_BLUEPRINT,
    'oauth2_access_tokens_list': helpers.SLIM_OAUTH2_TOKEN,
    'oauth2_authorization_codes_list': helpers.SLIM_OAUTH2_TOKEN,
    'oauth2_refresh_tokens_list': helpers.SLIM_OAUTH2_TOKEN,
    'outposts_instances_list': helpers.SLIM_OUTPOST,
    'outposts_ldap_list': helpers.SLIM_OUTPOST,
    'outposts_proxy_list': helpers.SLIM_OUTPOST,
    'outposts_radius_list': helpers.SLIM_OUTPOST,
    'outposts_service_connections_all_list': helpers.SLIM_SERVICE_CONNECTION,
    'outposts_service_connections_docker_list': helpers.SLIM_SERVICE_CONNECTION,
    'outposts_service_connections_kubernetes_list': helpers.SLIM_SERVICE_CONNECTION,
    'policies_all_list': helpers.SLIM_POLICY,
    'policies_bindings_list': helpers.SLIM_POLICY_BINDING,
    'policies_dummy_list': helpers.SLIM_POLICY,
    'policies_event_matcher_list': helpers.SLIM_POLICY,
    'policies_expression_list': helpers.SLIM_POLICY,
    'policies_geoip_list': helpers.SLIM_POLICY,
    'policies_password_expiry_list': helpers.SLIM_POLICY,
    'policies_password_list': helpers.SLIM_POLICY,
    'policies_reputation_list': helpers.SLIM_POLICY,
    'policies_reputation_scores_list': helpers.SLIM_REPUTATION_SCORE,
    'policies_unique_password_list': helpers.SLIM_POLICY,
    'propertymappings_all_list': helpers.SLIM_PROPERTY_MAPPING,
    'propertymappings_notification_list': helpers.SLIM_PROPERTY_MAPPING,
    'propertymappings_provider_google_workspace_list': helpers.SLIM_PROPERTY_MAPPING,
    'propertymappings_provider_microsoft_entra_list': helpers.SLIM_PROPERTY_MAPPING,
    'propertymappings_provider_rac_list': helpers.SLIM_PROPERTY_MAPPING,
    'propertymappings_provider_radius_list': helpers.SLIM_PROPERTY_MAPPING,
    'propertymappings_provider_saml_list': helpers.SLIM_PROPERTY_MAPPING,
    'propertymappings_provider_scim_list': helpers.SLIM_PROPERTY_MAPPING,
    'propertymappings_provider_scope_list': helpers.SLIM_PROPERTY_MAPPING,
    'propertymappings_source_kerberos_list': helpers.SLIM_PROPERTY_MAPPING,
    'propertymappings_source_ldap_list': helpers.SLIM_PROPERTY_MAPPING,
    'propertymappings_source_oauth_list': helpers.SLIM_PROPERTY_MAPPING,
    'propertymappings_source_plex_list': helpers.SLIM_PROPERTY_MAPPING,
    'propertymappings_source_saml_list': helpers.SLIM_PROPERTY_MAPPING,
    'propertymappings_source_scim_list': helpers.SLIM_PROPERTY_MAPPING,
    'propertymappings_source_telegram_list': helpers.SLIM_PROPERTY_MAPPING,
    'providers_all_list': helpers.SLIM_PROVIDER,
    'providers_google_workspace_list': helpers.SLIM_PROVIDER,
    'providers_ldap_list': helpers.SLIM_PROVIDER,
    'providers_microsoft_entra_list': helpers.SLIM_PROVIDER,
    'providers_oauth2_list': helpers.SLIM_PROVIDER,
    'providers_proxy_list': helpers.SLIM_PROVIDER,
    'providers_rac_list': helpers.SLIM_PROVIDER,
    'providers_radius_list': helpers.SLIM_PROVIDER,
    'providers_saml_list': helpers.SLIM_PROVIDER,
    'providers_scim_groups_list': None,
    'providers_scim_list': helpers.SLIM_PROVIDER,
    'providers_scim_users_list': None,
    'providers_ssf_list': helpers.SLIM_PROVIDER,
    'providers_wsfed_list': helpers.SLIM_PROVIDER,
    'rac_connection_tokens_list': helpers.SLIM_RAC_TOKEN,
    'rac_endpoints_list': helpers.SLIM_RAC_ENDPOINT,
    'rbac_initial_permissions_list': helpers.SLIM_PERMISSION,
    'rbac_permissions_assigned_by_roles_list': helpers.SLIM_PERMISSION,
    'rbac_permissions_list': helpers.SLIM_PERMISSION,
    'rbac_permissions_roles_list': helpers.SLIM_PERMISSION,
    'rbac_roles_list': helpers.SLIM_ROLE,
    'reports_exports_list': helpers.SLIM_EXPORT,
    'sources_all_list': helpers.SLIM_SOURCE,
    'sources_group_connections_all_list': helpers.SLIM_SOURCE_CONNECTION,
    'sources_kerberos_list': helpers.SLIM_SOURCE,
    'sources_ldap_list': helpers.SLIM_SOURCE,
    'sources_oauth_list': helpers.SLIM_SOURCE,
    'sources_plex_list': helpers.SLIM_SOURCE,
    'sources_saml_list': helpers.SLIM_SOURCE,
    'sources_scim_list': helpers.SLIM_SOURCE,
    'sources_telegram_list': helpers.SLIM_SOURCE,
    'sources_user_connections_all_list': helpers.SLIM_SOURCE_CONNECTION,
    'ssf_streams_list': helpers.SLIM_SSF_STREAM,
    'stages_all_list': helpers.SLIM_STAGE,
    'stages_authenticator_duo_list': helpers.SLIM_STAGE,
    'stages_authenticator_email_list': helpers.SLIM_STAGE,
    'stages_authenticator_endpoint_gdtc_list': helpers.SLIM_STAGE,
    'stages_authenticator_sms_list': helpers.SLIM_STAGE,
    'stages_authenticator_static_list': helpers.SLIM_STAGE,
    'stages_authenticator_totp_list': helpers.SLIM_STAGE,
    'stages_authenticator_validate_list': helpers.SLIM_STAGE,
    'stages_authenticator_webauthn_list': helpers.SLIM_STAGE,
    'stages_captcha_list': helpers.SLIM_STAGE,
    'stages_consent_list': helpers.SLIM_STAGE,
    'stages_deny_list': helpers.SLIM_STAGE,
    'stages_dummy_list': helpers.SLIM_STAGE,
    'stages_email_list': helpers.SLIM_STAGE,
    'stages_endpoints_list': helpers.SLIM_STAGE,
    'stages_identification_list': helpers.SLIM_STAGE,
    'stages_invitation_invitations_list': helpers.SLIM_STAGE,
    'stages_invitation_stages_list': helpers.SLIM_STAGE,
    'stages_mtls_list': helpers.SLIM_STAGE,
    'stages_password_list': helpers.SLIM_STAGE,
    'stages_prompt_prompts_list': helpers.SLIM_STAGE,
    'stages_prompt_stages_list': helpers.SLIM_STAGE,
    'stages_redirect_list': helpers.SLIM_STAGE,
    'stages_source_list': helpers.SLIM_STAGE,
    'stages_user_delete_list': helpers.SLIM_STAGE,
    'stages_user_login_list': helpers.SLIM_STAGE,
    'stages_user_logout_list': helpers.SLIM_STAGE,
    'stages_user_write_list': helpers.SLIM_STAGE,
    'tasks_schedules_list': helpers.SLIM_TASK,
    'tasks_tasks_list': helpers.SLIM_TASK,
}

DIRECT_PROJECTIONS = {
    'admin_version_history_list': helpers.SLIM_VERSION_HISTORY,
    'admin_file_list': helpers.SLIM_ADMIN_FILE,
}


def prepare_policy_binding_update(client, operation, body, query):
    # The serializer validates the complete subject/target even for partial updates.
    current = client.get(operation["path"])
    writable = {param["wire"] for param in operation["parameters"] if param["location"] == "body"}
    merged = {key: value for key, value in current.items() if key in writable}
    merged.update(body)
    return client.put(operation["path"], json=merged, params=query)


REQUEST_OVERRIDES = {
    "policies_bindings_partial_update": prepare_policy_binding_update,
}
